Repository lion5/component-library, pull requests merged in 2024-04, with the labels that each got.

#117 Update SelectInput.vue
  src/atoms/inputs/SelectInput/SelectInput.vue
Labels: bug

#142 :bug: fix(package config): unify package entry points and export them
  packages/core/package.json
  packages/core/vite.config.ts
  packages/firebase/package.json
  packages/firebase/vite.config.ts
  packages/gridstack/package.json
  packages/gridstack/vite.config.ts
  packages/leaflet/package.json
  packages/leaflet/vite.config.ts
Labels: bug

#147 Introduce NamedLocation and GPSLocation in gridstack package t…
  packages/gridstack/src/components/widgets/weather/widgets/DWDWarnFeedWidget/WeatherWarnFeedWidget.vue
  packages/gridstack/src/components/widgets/weather/widgets/DWDWarnFeedWidget/config.ts
  packages/gridstack/src/components/widgets/weather/widgets/WeatherForcastWidget/WeatherForecastWidget.vue
  packages/gridstack/src/components/widgets/weather/widgets/WeatherForcastWidget/config.ts
  packages/gridstack/src/components/widgets/weather/widgets/WeatherWidget/WeatherWidget.vue
  packages/gridstack/src/components/widgets/weather/widgets/WeatherWidget/config.ts
  packages/gridstack/src/models/gpsLocation.ts
  packages/gridstack/src/models/namedLocation.ts
Labels: bug

#118 Add features for persistence of Dashboard Configuration
  packages/gridstack/src/components/ConfigurableDashboard/ConfigurableDashboard.spec.ts
  packages/gridstack/src/components/ConfigurableDashboard/ConfigurableDashboard.stories.ts
  packages/gridstack/src/components/ConfigurableDashboard/ConfigurableDashboard.vue
  packages/gridstack/src/components/DashboardBar/DashboardBar.spec.ts
  packages/gridstack/src/components/DashboardBar/DashboardBar.vue
  packages/gridstack/src/components/EditButton/EditButton.vue
  packages/gridstack/src/components/SaveDashboardModal/SaveDashboardModal.vue
Labels: enhancement

#150 Move shared shared model, composables and components to core package
  package-lock.json
  packages/core/src/composables/index.ts
  packages/core/src/composables/useNominatim.ts
  packages/core/src/inputs/LocationCoordinateSelect/LocationCoordinateSelect.spec.ts
  packages/core/src/inputs/LocationCoordinateSelect/LocationCoordinateSelect.stories.ts
  packages/core/src/inputs/LocationCoordinateSelect/LocationCoordinateSelect.vue
  packages/core/src/inputs/index.ts
  packages/core/src/models/gpsLocation.ts
  packages/core/src/models/index.ts
  packages/core/src/models/namedLocation.ts
  packages/core/src/models/nominatimResult.ts
  packages/gridstack/src/components/widgets/weather/widgets/DWDWarnFeedWidget/WeatherWarnFeedWidget.vue
  packages/gridstack/src/components/widgets/weather/widgets/DWDWarnFeedWidget/config.ts
  packages/gridstack/src/components/widgets/weather/widgets/WeatherForcastWidget/WeatherForecastWidget.vue
  packages/gridstack/src/components/widgets/weather/widgets/WeatherForcastWidget/config.ts
  packages/gridstack/src/components/widgets/weather/widgets/WeatherWidget/WeatherWidget.vue
  packages/gridstack/src/components/widgets/weather/widgets/WeatherWidget/config.ts
  packages/leaflet/src/components/inputs/index.ts
  packages/leaflet/src/composables/index.ts
  packages/leaflet/src/models/index.ts
Labels: bug

#153 fix(leaflet,gridstack,firebase): :bug: add missing style exports
  packages/firebase/package.json
  packages/gridstack/package.json
  packages/leaflet/package.json
Labels: bug

#167 :memo: Add Docs for CSS Props
  README.md
  packages/core/src/assets/style/variables/_border.scss
  packages/core/src/assets/style/variables/_shadow.scss
  packages/core/src/assets/style/variables/_typography.scss
  packages/core/src/assets/style/variables/index.scss
  packages/core/src/components/buttons/CopyButton/CopyButton.spec.ts
  packages/core/src/components/buttons/CopyButton/CopyButton.stories.ts
  packages/core/src/components/buttons/CopyButton/CopyButton.vue
  packages/core/src/components/buttons/IconButton/IconButton.vue
  packages/core/src/components/icons/BaseIcon.stories.ts
  packages/core/src/components/icons/BaseIcon.vue
  packages/core/src/components/icons/IconCopy.vue
  packages/core/src/components/icons/index.ts
  packages/core/src/components/index.ts
  packages/core/src/stories/Colors.css
  packages/core/src/stories/Colors.mdx
  packages/storybook-host/.storybook/preview.ts
  packages/storybook-host/src/Border.css
  packages/storybook-host/src/Border.mdx
  packages/storybook-host/src/Imprint.mdx
  packages/storybook-host/src/Shadows.mdx
  packages/storybook-host/src/Spacing.css
  packages/storybook-host/src/Spacing.mdx
  packages/storybook-host/src/Typography.css
  packages/storybook-host/src/Typography.mdx
  packages/storybook-host/src/Welcome.mdx
  packages/storybook-host/src/assets/base.css
Labels: documentation
