Repository lion5/component-library, pull requests merged in 2025-01, with the labels that each got.

#249 chore(ListInputValidated): 🎉 add new input component
  packages/core/src/components/buttons/IconButton/IconButton.spec.ts
  packages/core/src/components/buttons/IconButton/IconButton.stories.js
  packages/core/src/components/buttons/IconButton/IconButton.stories.ts
  packages/core/src/components/buttons/IconButton/IconButton.vue
  packages/core/src/components/display/BasePill/BasePill.stories.ts
  packages/core/src/components/display/BasePill/BasePill.vue
  packages/core/src/components/icons/ArrowRotateLoadingAnimation.vue
  packages/core/src/components/index.ts
  packages/core/src/components/inputs/ListInputValidated/ListInputValidated.spec.ts
  packages/core/src/components/inputs/ListInputValidated/ListInputValidated.stories.ts
  packages/core/src/components/inputs/ListInputValidated/ListInputValidated.vue
  packages/core/src/components/inputs/ListInputValidated/PillListInput.spec.ts
  packages/core/src/components/inputs/ListInputValidated/PillListInput.vue
  packages/core/src/components/inputs/ListInputValidated/pillInputItem.ts
  packages/core/src/components/inputs/PillInput/PillInput.spec.ts
  packages/core/src/components/inputs/PillInput/PillInput.stories.ts
  packages/core/src/components/inputs/PillInput/PillInput.vue
  packages/core/src/components/inputs/index.ts
  packages/core/src/components/utils/EndButtonWrapper/EndButtonWrapper.spec.ts
  packages/core/src/components/utils/EndButtonWrapper/EndButtonWrapper.stories.ts
  packages/core/src/components/utils/EndButtonWrapper/EndButtonWrapper.vue
Labels: enhancement

#253 fix(ListInputValidated): make label optional to use slot
  packages/core/src/components/inputs/ListInputValidated/ListInputValidated.vue
Labels: bug

#255 fix(BaseButton): set default button type to button
  packages/core/src/components/buttons/BaseButton/BaseButton.vue
Labels: bug

#257 fix(EndButtonWrapper): export end button wrapper
  packages/core/src/components/index.ts
Labels: bug

#263 fix: set validation rules for generic inputs to undefined
  packages/core/src/components/inputs/BaseInputV3Validated/BaseInputV3Validated.vue
  packages/core/src/components/inputs/ListInputValidated/ListInputValidated.vue
  packages/core/src/components/inputs/MultiselectInputValidated/MultiselectInputValidated.vue
  packages/core/src/components/inputs/SelectInputValidated/SelectInputValidated.vue
Labels: bug

#264 Refactor/update login form input fields
  packages/core/src/components/molecules/LoginForm/LoginForm.spec.ts
  packages/core/src/components/molecules/LoginForm/LoginForm.vue
Labels: enhancement

#266 Chore: bump workflow upload artifact version
  .github/workflows/release.yml
Labels: dependencies

#273 fix(AddressInputValidate): emit address on input
  packages/core/src/components/inputs/AddressInputValidated/AddressInputValidated.spec.ts
  packages/core/src/components/inputs/AddressInputValidated/AddressInputValidated.vue
  packages/core/src/components/inputs/BaseInputV3Validated/BaseInputV3Validated.vue
Labels: bug

#278 feat(BasePill): introduce loading state
  packages/core/src/components/buttons/CopyButton/CopyButton.spec.ts
  packages/core/src/components/buttons/CopyButton/CopyButton.vue
  packages/core/src/components/display/BasePill/BasePill.spec.ts
  packages/core/src/components/display/BasePill/BasePill.stories.ts
  packages/core/src/components/display/BasePill/BasePill.vue
Labels: enhancement

#277 fix(AddressInput): Emit input finished event if address is fully typed
  packages/core/.storybook/decorators.ts
  packages/core/src/components/inputs/AddressInputValidated/AddressInputValidated.stories.ts
  packages/core/src/components/inputs/AddressInputValidated/AddressInputValidated.vue
  packages/core/src/components/inputs/BaseInputV3/BaseInputV3.vue
Labels: bug

#280 fix: Match Component Styles With BG Styles
  packages/core/src/components/cards/BaseCard/BaseCard.vue
  packages/core/src/components/cards/EditableEntityCard/EditableEntityCard.spec.ts
  packages/core/src/components/cards/EditableEntityCard/EditableEntityCard.stories.ts
  packages/core/src/components/cards/EditableEntityCard/EditableEntityCard.vue
  packages/core/src/components/cards/EntityCard/EntityCard.vue
  packages/core/src/components/display/ContentGroup/ContentGroup.stories.ts
  packages/core/src/components/display/ContentGroup/ContentGroup.vue
  packages/core/src/components/dropdown/DropDown/DropDown.vue
  packages/core/src/components/index.ts
  packages/core/src/components/inputs/index.ts
  packages/core/src/components/utils/EntityWrapper/EntityWrapper.vue
Labels: bug

#283 fix(EditableEntityCard): resolve style conflict with EntityCard
  packages/core/src/components/cards/EditableEntityCard/EditableEntityCard.vue
Labels: bug

#281 fix(SelectInput): adjust width based on chars & label z-index overlap
  packages/core/src/components/inputs/SelectInput/SelectInput.vue
Labels: bug

#285 Feat/add required attribute input fields
  package-lock.json
  packages/core/package.json
  packages/core/src/components/inputs/BaseInputV3/BaseInputV3.stories.ts
  packages/core/src/components/inputs/BaseInputV3/BaseInputV3.vue
  packages/core/src/components/inputs/BaseInputV3Validated/BaseInputV3Validated.stories.ts
  packages/core/src/components/inputs/BaseInputV3Validated/BaseInputV3Validated.vue
  packages/core/src/components/inputs/CentInputValidated/CentInputValidated.stories.ts
  packages/core/src/components/inputs/CentInputValidated/CentInputValidated.vue
  packages/core/src/components/inputs/CheckboxInputV2Validated/CheckboxInputV2Validated.stories.ts
  packages/core/src/components/inputs/CheckboxInputV2Validated/CheckboxInputV2Validated.vue
  packages/core/src/components/inputs/DateTimeInputValidated/DateTimeInputValidated.stories.ts
  packages/core/src/components/inputs/DateTimeInputValidated/DateTimeInputValidated.vue
  packages/core/src/components/inputs/EuroInputValidated/EuroInputValidated.stories.ts
  packages/core/src/components/inputs/EuroInputValidated/EuroInputValidated.vue
  packages/core/src/components/inputs/IbanInputValidated/IbanInputValidated.stories.ts
  packages/core/src/components/inputs/IbanInputValidated/IbanInputValidated.vue
  packages/core/src/components/inputs/MultiselectInput/MultiselectInput.stories.ts
  packages/core/src/components/inputs/MultiselectInput/MultiselectInput.vue
  packages/core/src/components/inputs/MultiselectInputValidated/MultiselectInputValidated.stories.ts
  packages/core/src/components/inputs/MultiselectInputValidated/MultiselectInputValidated.vue
  packages/core/src/components/inputs/SelectInput/SelectInput.stories.ts
  packages/core/src/components/inputs/SelectInput/SelectInput.vue
  packages/core/src/components/inputs/SelectInputValidated/SelectInputValidated.stories.ts
  packages/core/src/components/inputs/SelectInputValidated/SelectInputValidated.vue
  packages/core/src/components/inputs/SlugInputValidated/SlugInputValidated.stories.ts
  packages/core/src/components/inputs/SlugInputValidated/SlugInputValidated.vue
  packages/core/src/components/inputs/TextareaInput/TextareaInput.stories.ts
  packages/core/src/components/inputs/TextareaInput/TextareaInput.vue
  packages/core/src/components/inputs/TextareaInputValidated/TextareaInputValidated.stories.ts
  packages/core/src/components/inputs/TextareaInputValidated/TextareaInputValidated.vue
Labels: enhancement
